### PR TITLE
Update .gitignore

### PR DESCRIPTION
**Pull request by burningdevil**

### CODE REVIEW

**Comment by burningdevil** [comment]
comemnt 1

**Review by leen1218 — APPROVED** [review]
approved.

**Comment by burningdevil** [comment]
@burningdevil abcd

**Comment by burningdevil** [comment]
@burningdevil cdefg

**Comment by burningdevil** [comment]
@burningdevil  what's wrog

**Comment by burningdevil** [comment]
@burningdevil  what's wrong

**Comment by burningdevil** [comment]
@burningdevil  a

**Comment by burningdevil** [comment]
@burningdevil  as

**Comment by burningdevil** [comment]
@burningdevil asd

**Comment by burningdevil** [comment]
@burningdevil  test

**Comment by burningdevil** [comment]
@burningdevil  ah

**Comment by burningdevil** [comment]
@burningdevil  a comment

**Comment by burningdevil** [comment]
a comment

**Comment by burningdevil** [comment]
@burningdevil  a

**Comment by burningdevil** [comment]
@burningdevil  a

**Comment by burningdevil** [comment]
@burningdevil  a

**Comment by burningdevil** [comment]
@burningdevil  acd

**Comment by burningdevil** [comment]
@burningdevil  cd

**Comment by burningdevil** [comment]
@burningdevil  a c

**Pull request closed without merging**
